### ISSUE TITLE
看了好几个 Tabs 实现方案了，奈何没一个具体的从官方脚手架无缝升级的文档

### ISSUE THREAD

**Issue by theprimone** [ts-react/react-admin-template#119]
看样子得自己又造轮子吗？_(:3J∠)_

**Comment by wangxingkang** [comment]
不好做到无缝升级只能做到 尽可能的少改动

**Comment by wangxingkang** [comment]
有好的方案 可以探讨一下 一起实现

**Comment by theprimone** [comment]
那为什么不整一个升级文档介绍一下思路呢？

**Comment by wangxingkang** [comment]
好的 抽时间整理一个

**Comment by wangxingkang** [comment]
https://github.com/ts-react/react-admin-template/issues/122 看看还有什么需要説明的

**Comment by theprimone** [comment]
看你参考的 https://github.com/kuhami/react-ant 这个仓库，我用的他的方式，刚跑通了:laughing:正在优化中。

不过看你用的思路是 localstorage，应该没必要吧，感觉 state 挺好的。

**Comment by wangxingkang** [comment]
主要解决刷新数据丢失问题

**Comment by wangxingkang** [comment]
可以加入钉钉群聊，有问题多沟通!

**Comment by theprimone** [comment]
还是比较喜欢社区的感觉，再说没用钉钉，谢谢啦
